##
# This workflow builds and tests docker images and pushes analyzer and pipeline to AWS ECR.
##

name: Test git config

# Triggered by a published release (pre-release).
on:
  push:
    branches: [ master, develop ]

jobs:

  test_git_config:
    name: test git config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add something
        run: |
          mkdir test
          cd ./test
          touch text.txt

      - name: Commit and push to remote branch gh-pages
        run: |
          git config --global user.name 'wf1_release'
          git config --global user.email 'workflow@viadee.de'
          git add *
          git status
          git commit -m"update from workflow"
          git push